### Get All Games
GET https://localhost:5218/games
Accept: application/json

###

### Get a Game by ID
GET https://localhost:5218/games/1
Accept: application/json

###

### Create a New Game
POST https://localhost:5218/games
Content-Type: application/json

{
    "Name": "StreetFighter I",
    "GenreId": 1,
    "Price": 17.24,
    "ReleaseDate": "2015-11-30"
}

###

### Update an Existing Game
PUT https://localhost:5218/games/2
Content-Type: application/json

{
    "Name": "Minecraft Me",
    "GenreId": 2,
    "Price": 15.24,
    "ReleaseDate": "2015-11-30"
}

###

### Delete a Game
DELETE https://localhost:5218/games/2
