GET http://localhost:5218/games
###

GET http://localhost:5218/games/5

###
POST http://localhost:5218/games
Content-Type: application/json

{
    "Name" : "Minecraft",
    "Genre" : " Kids and Family",
    "price" : 10.24,
    "ReleaseDate" : "2015-11-30"
}

###
PUT http://localhost:5218/games/5
Content-Type: application/json

{
    "Name" : "Minecraft II",
    "Genre" : " Kids and Family",
    "price" : 15.24,
    "ReleaseDate" : "2015-11-30"
}



###
DELETE http://localhost:5218/games/1