GET http://localhost:5218/games
###

GET http://localhost:5218/games/1

###
POST http://localhost:5218/games
Content-Type: application/json

{
    "Name" : "StreetFighter I",
    "GenreId" : 1,
    "price" : 17.24,
    "ReleaseDate" : "2015-11-30"
}

###
PUT http://localhost:5218/games/1
Content-Type: application/json

{
   "Name" : "Minecraft Me",
    "GenreId" : 2,
    "price" : 15.24,
    "ReleaseDate" : "2015-11-30"
}



###
DELETE http://localhost:5218/games/2